Objetivo 0 Readme Sin Link
alvarogaro/AGR-MVS pull request #1
Opened 2022-09-17 18:23 UTC by alvarogaro

Objetivo 0 completado a falta de poner el link de las imagenes

2022-09-19 11:46 UTC, alvarogaro commented
Objetivo 0 Completo

2022-09-20 10:45 UTC, JJ commented
La lista de comprobación es para que la sigáis y la pongáis. Si no empezáis por hacer eso, es bastante difícil que hayáis alcanzado los objetivos.

2022-09-20 10:48 UTC, JJ requested changes
El proceso de "design thinking" está hecho para poder llegar a entender problemas y buscar soluciones. Por favor, síguelo para encontrar un problema que puedas resolver a lo largo de la asignatura.

2022-09-20 10:48 UTC, JJ commented on README.md
> +La solución que se propone en un inicio es la creación de un servicio que permita a las franquicias inscribir sus distintas tiendas y poder añadir los usuarios que hay en el local a la aplicación (Bi
El problema es factible, pero la solución no tiene mucho sentido. Aparte de que la lógica de negocio sería simplemente "almacenar y buscar"

2022-09-20 17:30 UTC, alvarogaro commented on README.md
> +La solución que se propone en un inicio es la creación de un servicio que permita a las franquicias inscribir sus distintas tiendas y poder añadir los usuarios que hay en el local a la aplicación (Bi
El caso es que con el problema planteado, ¿Debería de busca una solución que contenga "calculo o procesamiento de datos", o cual es el enfoque que debería de dar a mi solución?

2022-09-21 07:48 UTC, JJ commented on README.md
> +La solución que se propone en un inicio es la creación de un servicio que permita a las franquicias inscribir sus distintas tiendas y poder añadir los usuarios que hay en el local a la aplicación (Bi
Eso es lo que dice el guión, ¿no?

2022-09-22 09:47 UTC, JJ approved these changes
Recuerda que tienes que usar un modelo realista y datos realistas, y que tienes que tratar de implementar tú las fórmulas que usen la teoría de colas.
También os agradecería que pidierais explícitamente revisión, con un comentario o desde el formulario.

2022-09-22 11:19 UTC, alvarogaro commented
@JJ Entonces quedaría aprobado y podría hacer el merge ??

2022-09-22 15:26 UTC, JJ commented
![Captura de pantalla de 2022-09-22 17-26-45](https://user-images.githubusercontent.com/500/191788480-a0cfa31f-25f4-4872-8f5e-b94a0b13ea9a.png)
:+1:

2022-09-23 07:10 UTC, merged