Objetivo_3_AGR
alvarogaro/AGR-MVS pull request #15
Opened 2022-11-12 19:32 UTC by alvarogaro

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [*] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [*] ¿Ese issue está asignado a un milestone?
* [*] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [*] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [*] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [*] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?

2022-11-13 16:51 UTC, alvarogaro commented
@JJ listo para revision

2022-11-14 08:05 UTC, JJ requested changes
Tenéis que intentar creeros lo que escribís, no escribir simplemente cosas.

2022-11-14 08:05 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* PipEnv: Este gestor de dependencias de python, mirando un poco su [documentación](https://pipenv.pypa.io/en/latest/index.html), podemos ver como su funcionamiento se basa en la presencia de un fich
¿Para qué lo mencionas entonces, si no cumple lo mínimo?

2022-11-14 08:05 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Poetry: Gestor de dependencias, igual que hatch hace uso de un fichero pyproject.toml, al igual que su estructura de ficheros es la recomendada por las buenas prácticas, mediante poetry, podemos ag
No me repitas lo que pone en la descripción. Limítate a decir si cumple o no tus requisitos.

2022-11-14 08:05 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Finalmente hemos descartado pipenv por no seguir las buenas prácticas y nos queda realizar una comparación entre Poetry y Hatch.
Es que no tenías que haberlo mencionado.

2022-11-14 08:05 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Poetry: Nos ofrece entornos virtuales de manera automática en la configuración, permite tener una mejor experiencia frente a árboles de dependencia complejos y tiene un uso eficiente de almacenamie
Los criterios objetivos que has mencionado son los PEPs. No puedes usar cosas que no has mencionado, como "mejor experiencia" o "entornos virtuales", para elegir uno u otro.

2022-11-14 08:05 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Hatch: Se define como un manejador de proyectos con su propio manejador de dependencias. Hatch además incorporá funcionalidades como un sistema de test y herramientas para cobertura de código. Hatc
En este apartado estás comparando. No vuelvas a repetir lo que es, y menos si no sirve para elegirlo o no.
Ninguna de las cosas que mencionas están en los criterios. ¿Qué sistema de test incluye? ¿Eso está en los PEPs que has puesto como criterios objetivos?

2022-11-14 08:05 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Finalmente, hemos escogido Poetry como gestor de dependencias, ya que nos permite reducir la deuda técnica, es bastante sencillo a la hora de expresar dependencias y es el gestor con mayor puntuaci
¿Cómo te permite reducir la deuda técnica de una forma que hatch no?

2022-11-15 11:22 UTC, alvarogaro commented
@JJ, ya he modificado la elección y está listo de nuevo para revisión.

2022-11-15 12:37 UTC, JJ requested changes
Aparte de los temas de detalle y de expresión, sigues sin establecer unos criterios objetivos previos a la elección.

2022-11-15 12:37 UTC, JJ commented on README.md
> +* Luego para instalar nuestro proyecto simplemente tendremos que ejecutar el comando
ESto no instala el proyecto. Por favor, infórmate de qué hace cada cosa.

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Como hemos planteado en el issue [#12](https://github.com/alvarogaro/AGR-MVS/issues/12), va a ser necesario la elección de un gestor de dependencias para nuestro proyecto, esto es necesario ya que
"mayor" no. Es que no te queda otro remedio. ¿Cómo gestionas las dependencias sin gestor de dependencias?
De verdad, esto no es un TFG. Poned lo necesario para evaluar el objetivo.

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Para la elección de nuestro gestor de dependencias, tenemos que basarnos en criterios objetivos y de las mejores prácticas del lenguaje que estemos utilizando en nuestro proyecto.
¿Es necesario que pongáis los criterios de evaluación para que os evalúe?

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Dependencias.md
> +## Comparativa Gestores De Dependencias.
Las mayúsculas Arbitrarias son Algo irritantes. Sin mayor importancia.

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Poetry: En esta siguiente comparativa nos vamos a basar en su análisis en Snyk podemos ver que tiene una puntuación de 97, una gran popularidad y un mantenimiento activo.
¿Dónde has establecido la puntuación de Snyk como criterio objetivo?
O sea, has puesto un párrafo diciendo que ibas a usar criterios objetivos (innecesario) pero *no* has establecido la puntuación de Snyk como criterio objetivo (necesario).

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Poetry: Gestor de dependencias, igual que como hemos hecho con Hatch, vemos que cumple los PEP mencionados anteriormente.
Estos tres párrafos podías ahorrártelos con una frase que dijera: este y este cumplen los criterios.

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Finalmente, tanto Hatch como Poetry son dos Gestores de Dependencias que nos van a servir perfectamente para nuestro proyecto y que cumplen con los PEP mencionados anteriormente. Sin embargo me voy
Si la "integración" es otro criterio objetivo, también tendrás que enunciarlo *de antemano*, no para justificar lo que ya habías decidido previamente.

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Tareas.md
> +* En este documentos vamos a realizar un análisis de los Gestores de Tareas que hemos mencionado en el issue [#13](https://github.com/alvarogaro/AGR-MVS/issues/13). Para este análisis vamos a tocar t
¿Dónde estás "tocando" esos "temas"?

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Tareas.md
> +* Pypyr: Este Gestor ha aumentado su popularidad recientemente, especialmente en octubre de 2022. Revisando su repositorio vemos que ha tenido un gran numero de commits en Octubre de 2022 lo que nos
Podías enlazar la página de cada uno, ya puesto.

2022-11-15 12:37 UTC, JJ commented on docs/Gestor-Tareas.md
> +* Por todo lo expuesto anteriormente, utilizaremos Poethepoet como gestor de tareas para nuestro proyecto, ya que nos permite reducir la deuda técnica de nuestro proyecto, teniendo en cuenta nuestras
Si ya lo habías dicho antes. ¿Dónde están los criterios objetivos?

2022-11-15 12:37 UTC, JJ commented on docs/Test-Runner.md
> +Como se ha comentado en el issue [#14](https://github.com/alvarogaro/AGR-MVS/issues/14) vamos a realizar un análisis de los Test Runners comentados y a elegir el mejor para el proyecto:
No es de este objetivo.

2022-11-15 12:37 UTC, JJ commented on pyproject.toml
> +pytest = "7.0"
No es de este objetivo.

2022-11-15 12:37 UTC, JJ commented on tests/test-syntax.py
> +import os
No estás usando esto.

2022-11-15 16:55 UTC, alvarogaro commented on docs/Gestor-Dependencias.md
> +* Como hemos planteado en el issue [#12](https://github.com/alvarogaro/AGR-MVS/issues/12), va a ser necesario la elección de un gestor de dependencias para nuestro proyecto, esto es necesario ya que
Entonces simplemente tengo que eliminar esta introducción??

2022-11-16 11:15 UTC, arsa-dev approved these changes
👍 👍 Ya veo corregidos todos los puntos que @JJ te comentó, supongo que ya está listo para su revisión.

2022-11-16 11:15 UTC, arsa-dev commented on docs/Gestor-Dependencias.md
> +* Finalmente, tanto Hatch como Poetry son dos Gestores de Dependencias que nos van a servir perfectamente para nuestro proyecto y que cumplen con los PEP mencionados anteriormente. Sin embargo me voy
Veo que ya se ha añadido en el tercer enunciado

2022-11-16 11:15 UTC, arsa-dev commented on docs/Gestor-Dependencias.md
> +* Poetry: En esta siguiente comparativa nos vamos a basar en su análisis en Snyk podemos ver que tiene una puntuación de 97, una gran popularidad y un mantenimiento activo.
Ya lo veo añadido en el cuarto párrafo de este fichero 👍

2022-11-16 11:15 UTC, arsa-dev commented on docs/Gestor-Dependencias.md
> +* Poetry: Gestor de dependencias, igual que como hemos hecho con Hatch, vemos que cumple los PEP mencionados anteriormente.
👍

2022-11-16 11:15 UTC, arsa-dev commented on docs/Gestor-Tareas.md
> +* Por todo lo expuesto anteriormente, utilizaremos Poethepoet como gestor de tareas para nuestro proyecto, ya que nos permite reducir la deuda técnica de nuestro proyecto, teniendo en cuenta nuestras
Ya veo los criterios objetivos en los tres primeros párrafos 👍

2022-11-16 11:19 UTC, JJ commented on docs/Gestor-Tareas.md
> +* Por todo lo expuesto anteriormente, utilizaremos Poethepoet como gestor de tareas para nuestro proyecto, ya que nos permite reducir la deuda técnica de nuestro proyecto, teniendo en cuenta nuestras
Ya, pero ya había dicho en en el gestor de dependencias que lo elegía porque permitía usar fácilmente poethepoet. Si ya estaba elegido, ¿para qué poner criterios?

2022-11-16 15:52 UTC, alvarogaro commented
@JJ, listo para revisión de nuevo

2022-11-16 16:49 UTC, JJ requested changes
Las razones para elegir uno y otro son circulares: elijes poetry porque "se integra con" `poethepoet`, y eliges `poethepoet` porque se integra con `poetry`. 
He hecho [esta pregunta](https://github.com/nat-n/poethepoet/issues/103) en poethepoetry para que me lo aclaren.
El problema principal, de todas formas, es que las instrucciones que has puesto en el README están incompletas. Y es importante que estén completas, sobre todo porque tú mismo vas a tener que seguirlas en el objetivo 5 para crear la imagen Docker.

2022-11-16 16:49 UTC, JJ commented on README.md
> +* Luego para instalar las dependencias de nuestro proyecto simplemente tendremos que ejecutar el comando
*Luego* no.
Si incluís instrucciones, probad que sean correctas.

2022-11-16 16:49 UTC, JJ commented on docs/Gestor-Dependencias.md
> +## Comparativa Gestores De Dependencias.
... pero podías haberlo cambiado en vez de cerrarlo.

2022-11-16 16:49 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Adicionalmente a los criterios anteriormente mencionados, vamos a tener en cuenta el análisis que se hace  de estos gestores en [Synk](https://snyk.io/), en concreto nos vamos a fijar en su puntuac
typo: snyk

2022-11-16 16:49 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* En concreto, estamos tratando ahora la gestión de dependencias, por tanto vamos a seguir las recomendaciones que vienen recogidas en los PEP [517](https://peps.python.org/pep-0517/), [518](https://
Si quieres que "salga" poe, al menos hazlo bien. Los "gestores" no se integran con nada. Simplemente, poe usa el mismo fichero que los gestores de dependencias.
Poe puede funcionar sin poetry, de hecho.

2022-11-16 16:49 UTC, JJ commented on docs/Gestor-Dependencias.md
> +* Finalmente, tanto Hatch como Poetry son dos Gestores de Dependencias que nos van a servir perfectamente para nuestro proyecto y que cumplen con los PEP mencionados anteriormente. Sin embargo me voy
Mal añadido, porque poetry no se integra con nada. En ese sentido, hatch usa el mismo fichero `pyproject.toml` con lo que se "integra" exactamente igual.

2022-11-16 16:49 UTC, JJ commented on docs/Gestor-Tareas.md
> +* En este documentos vamos a realizar un análisis de los Gestores de Tareas que hemos mencionado en el issue [#13](https://github.com/alvarogaro/AGR-MVS/issues/13).
Que pongas mayúsculas en el titular todavía tiene un pase. Mal pase, pero lo tiene. Pero ¿en el interior de un párrafo?

2022-11-16 16:49 UTC, JJ commented on docs/Gestor-Tareas.md
> +* [Poethepoet](https://snyk.io/advisor/python/poethepoet): Gestor de Tareas bastante interesante debido a que puede trabajar conjuntamente con Poetry. Su popularidad es bastante alta y tiene registra
¿Por qué no puede trabajar con hatch?

2022-11-16 16:49 UTC, JJ commented on pyproject.toml
> +lock =  "poetry lock"
???

2022-11-16 16:52 UTC, JJ commented on pyproject.toml
> +poethepoet = "poethepoet.plugin:PoetryPlugin"
¿Has mirado lo que implica que sea un plugin y qué hay que hacer para que funcione como tal?

2022-11-17 08:47 UTC, JJ approved these changes
👍

2022-11-17 12:50 UTC, JJ commented on .gitignore
> +src/__pycache__
Basta con que pongas el nombre de fichero aquí.

2022-11-19 11:38 UTC, merged