[IV-22-23] Objetivo_1_AGR
alvarogaro/AGR-MVS pull request #2
Opened 2022-09-30 17:48 UTC by alvarogaro

2022-10-04 11:50 UTC, JJ commented
En todos los objetivos es imprescindible la lista de comprobación.

2022-10-04 11:52 UTC, alvarogaro commented
Perdon, es que la había  completado en el otro PR

2022-10-04 15:23 UTC, alvarogaro commented
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario? No, ya que solo tengo una historia de usuario y la tengo asignada al milestone 1
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos? Hay cierto salto entre ellos
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x]  ¿El milestone 0 es mínimo *y* viable?
* [x]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2022-10-04 17:50 UTC, JJ commented
En *el cuerpo* del PR

2022-10-05 06:11 UTC, JJ requested changes
Por favor, repasa el concepto de "producto" y úsalo para los milestones.

2022-10-05 06:11 UTC, JJ commented on doc/Conf-Github.md
> +- [Configuración SSH](https://github.com/alvarogaro/AGR-MVS/blob/objetivo_0_AGR/images/clave-ssh-github.jpg)
Esto no es necesario en este objetivo.

2022-10-05 06:11 UTC, JJ commented on doc/Milestones.md
> +* [[M0] Estructura de Datos para representar la información de las tiendas](https://github.com/alvarogaro/AGR-MVS/milestone/1)
Una estructura de datos no es un producto.

2022-10-05 06:11 UTC, JJ commented on doc/Milestones.md
> +* [[M1] Implementación de algoritmos  para obtener conclusiones a raiz de los datos](https://github.com/alvarogaro/AGR-MVS/milestone/2)
Tienes que describir en qué producto se implementan los algoritmos.

2022-10-05 06:11 UTC, JJ commented on doc/Milestones.md
> +* [[M2] Representación global de los datos obtenidos por cada franquicia](https://github.com/alvarogaro/AGR-MVS/milestone/3)
Una vez más, no describes un producto.

2022-10-06 07:51 UTC, arsa-dev commented
@alvarogaro Yo lo que creo que falta principalmente es que ahora mismo los milestones se están pensando en cuanto a lo que se hace durante ellos y no en cuanto a lo que se entrega o se genera mediante ellos. Aunque no sea algo usable por el cliente en el M0 por ejemplo podrías generar/entregar un módulo. En el M1 podrías entregar una API que permita hacer uso de esa lógica o una líbrería de funciones, etc. En el M3 podrías entregar un fichero en un determinado formato que sea el que represente esa información.

2022-10-06 15:15 UTC, alvarogaro commented
@JJ he hecho algunas modificaciones según el consejo de @arsa-dev y ya esta listo para revisión de nuevo

2022-10-06 18:00 UTC, JJ approved these changes
Podrías precisar un poco más, pero más o menos está superado.

2022-10-06 18:00 UTC, JJ commented on docs/Historias-Usuario.md
> +Es nuestro principal cliente, puede ser cualquier cualquier operadora de franquicias, como por ejemplo Burguer-King, Macdonald's, KFC, etc... Nuestro cliente busca el uso de la aplicación ya que pret
typo en Burguer

2022-10-06 18:00 UTC, JJ commented on docs/Milestones.md
> +* [[M0] Módulo para representar la información de las tiendas](https://github.com/alvarogaro/AGR-MVS/milestone/1)
"Las tiendas" no es un modelo completo del problema, es posible que haya que representar más cosas.

2022-10-10 09:54 UTC, merged