[IV-22-23] Objetivo 2 de @pablo1mc315 en repositorio de @alvarogaro
alvarogaro/AGR-MVS pull request #5
Opened 2022-10-14 10:55 UTC by pablo1mc315

# Lista de Comprobación

## Prerrequisitos

* [x] Se tendrá que haber avanzado en el objetivo 1 antes de poder entregar este.

## Sobre la estructura del repositorio

* [ ] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
   disposición de los mismos?

## Sobre el análisis del problema

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

## Sobre la planificación y la programación

* [ ] ¿Los issues representan un problema, y no una tarea?
* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están asignados a una HU?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit? Los issues sobre los que estoy trabajando, ¿han
      sido asignados al primer milestone?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Son los milestones sobre los que estoy trabajando productos
   mínimamente viables? ¿O tengo que solicitar al product manager que
   cree milestones adicionales o precise de qué producto se trata?

2022-10-14 11:02 UTC, pablo1mc315 commented
Buenas @alvarogaro. Este es el PR donde irán apareciendo las modificaciones que realice sobre el proyecto para crear la estructura de datos. Te iré abriendo varios ISSUES para ir discutiendo cuestiones acerca del proyecto :construction: 💪🏼

2022-10-25 15:25 UTC, pablo1mc315 commented
Buenas @alvarogaro, échale un ojo a ver que te parece lo que llevo de momento y cualquier cosa me dices (si encuentras algún getter que no sea necesario o si algún atributo no se ajusta a lo que deseas).

También necesito que añadas el PR al M0 para cuando realice la entrega y también que encuentres una base de datos cuanto antes, como te digo en #9, para hacer que la estructura de datos se ajuste lo máximo posible a ella. Un saludo! 😶‍🌫️ 🐧

2022-10-26 15:50 UTC, alvarogaro commented
Respecto a la base de datos creo que para este objetivo no va a ser necesario ( De todas formas lo hablaré con JJ) , con que se ajuste a los requisitos de las  historias de usuario será suficiente. He estado echándole un ojo al PR y la verdad que en un principio lo veo bien, excepto el enumerado que te lo he comentado el resto lo veo bien, de todas formas ya tendría el profesor que echarle un vistazo a ver que tal lo ve

2022-10-26 15:55 UTC, alvarogaro approved these changes
Revisar el Enumerado

2022-10-26 15:55 UTC, alvarogaro commented on src/enums/enum_turno.py
> +from enum import Enum
Para el enumerado, había pensado simplemente realizar algo así: 
```
Turnos = ["Maniana", "Tarde", "Noche"]
```

2022-10-26 19:50 UTC, pablo1mc315 commented on src/enums/enum_turno.py
> +from enum import Enum
No lo he hecho así ya que me parece que está mejor encapsulado así en un enumerado que en una "variable global". Una vez que encuentres realmente un .csv que se ajuste a tus necesidades, bastaría con modificar los valores de MANIANA, TARDE y NOCHE por los que vengan en tus datos y así está más accesible

2022-10-26 20:06 UTC, pablo1mc315 commented
@JJ listo para revision

2022-10-27 05:19 UTC, JJ commented
> # Lista de Comprobación
> ## Prerrequisitos
> * [x]  Se tendrá que haber avanzado en el objetivo 1 antes de poder entregar este.
> 
> ## Sobre la estructura del repositorio
> * [x]  ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
>   disposición de los mismos?
> 
> ## Sobre el análisis del problema
> * [x]  ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
>   que se ha creado?
>   Sí, en [[M0 - Dev] Objetivo de la aplicación #8](https://github.com/alvarogaro/AGR-MVS/issues/8).
> * [ ]  ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
>   una entidad o un agregado?

En la misma configuración del repo se tiene que decir qué entidad se ha programado, en el iv.yaml. Si no lo es, ¿qué fichero has puesto?

Si no has seguido DDD, ¿qué metodología se ha seguido?

2022-10-27 05:27 UTC, pablo1mc315 commented
En el iv.yaml aparece qué entidades se han programado y cuales son los objetos valor. No sabía que esa casilla de la lista de comprobación se refería a eso, así que no la marqué, fallo mío, procedo a marcarla @JJ

2022-10-27 21:56 UTC, pablo1mc315 commented
Se han enlazado los issues con la HU y se han reabierto los que estaban cerrados (fallo mío), los cuales se cerrarán cuando se haga mergee el  PR en el commit correspondiente o en el cuerpo del mismo. Listo para revisión @JJ

2022-10-28 05:09 UTC, JJ commented on src/enums/enum_turno.py
> +from enum import Enum
Quien lleve el repo sólo tiene que interpretar la lógica de negocio. No puede imponer ni decir "había pensado". Es la persona que programa la que tiene que decidir los detalles de implementación.

2022-10-28 05:11 UTC, JJ requested changes
Por favor, limitaros a poner en este objetivo lo solicitado en el guión en vez de copiar lo que otras personas han hecho.

2022-10-28 05:11 UTC, JJ commented on iv.yaml
> +objeto valor:
Esto ni hay que ponerlo, ni sé por qué os lo habéis copiado unos a otros poniéndolo, ni es correcto

2022-10-28 07:17 UTC, pablo1mc315 commented
@JJ listo para revision de nuevo! 🙂

2022-10-28 07:45 UTC, JJ approved these changes
@pablo1mc315 ha seguido el protocolo y buenas prácticas habituales para realizar algo que no avanza para nada el proyecto y no cubre el milestone. Pero el objetivo a cubrir es suyo, así que 👍

2022-10-28 07:45 UTC, JJ commented on iv.yaml
> +  - src/tienda.py
Esto es un array en YAML. Si tiene un solo elemento puedes ponerlo directamente como valor.

2022-10-28 07:45 UTC, JJ commented on src/empleado.py
> +@dataclass
Esta dataclass no está "frozen" y por tanto es mutable.
También, por lo hablado, no creo que sirva para la lógica de negocio ni tiene ninguna relación con lo expresado en el milestone actual.

2022-10-28 07:45 UTC, JJ commented on src/empresa.py
> +        return self.nombre
¿En qué parte de la lógica de negocio se usa el nombre de la empresa?

2022-10-28 08:10 UTC, pablo1mc315 commented
@alvarogaro listo para mergear cuando quieras

2022-10-29 16:25 UTC, merged